server:
  port: 9999
spring:
  datasource:
    url: jdbc:postgresql://prodpublicpg10bj.pg.rds.aliyuncs.com:3433/commonpay
    username: commonpay
    password: e3h4u6p7
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

app:
  config:
    #长沙银行支付网关地址
    csBankUrl: https://pbank.bankofchangsha.com
    #畅捷通开放平台地址
    chanjetOpenUrl: https://openapi.chanjet.com
    #畅捷通开放平台appKey
    appKey: r6qKN2wq
    #畅捷通开放平台appSecret
    appSecret: 09EDA89E3863A4D76192DAA7C91C24AF
    #加解密key
    encryptKey: csbankeytwuxrsy4
    #长沙银行支付结果推送地址
    backUrl: https://csbank-pay.chanapp.chanjet.com/api/message/test
    #Oauth重定向地址
    redirectUri: https://csbank-pay.chanapp.chanjet.com/api/auth/receiveCode
    #前端url
    frontUrl: /chslist
    #撤销订单url
    orderCancelUrl: /directBank/paygate/v0/doOrderCancel.do
    #付款码支付url
    orderPayUrl: /directBank/paygate/v0/orderPay.do
    #查询支付订单url
    queryOrderUrl: /directBank/paygate/v0/orderQueryWithSign.do
    #查询退款订单url
    queryRefundOrderUrl: /directBank/paygate/h5/thirdpartyQueryRefundOrder.do
    #退款url
    requestRefundUrl: /directBank/paygate/h5/thirdpartyRefund.do
