server:
  port: 9999
spring:
  datasource:
    url: jdbc:postgresql://pgm-2ze1c5g56k8qi62814790.pg.rds.aliyuncs.com:3433/developer_center
    username: developer_center
    password: g4u5w2m3
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

app:
  config:
    #畅捷通开放平台地址
    chanjetOpenUrl: https://inte-openapi.chanjet.com
    #畅捷通开放平台appKey
    appKey: hdxtXDas
    #畅捷通开放平台appSecret
    appSecret: 10FBDBD5C316ABD58E29BC488B723C91
    #加解密key
    encryptKey: 9876543210987654
    #Oauth重定向地址
    redirectUri: https://inte-csbank-pay.chanapp.chanjet.com/api/auth/receiveCode
    #前端url
    frontUrl: /chslist



