server:
  port: 9999
spring:
  datasource:
    url: jdbc:postgresql://pgm-2ze1c5g56k8qi62814790.pg.rds.aliyuncs.com:3433/developer_center
    username: developer_center
    password: g4u5w2m3
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

app:
  config:
    #长沙银行支付网关地址
    csBankUrl: http://test.bankofchangsha.com
    #畅捷通开放平台地址
    chanjetOpenUrl: https://inte-openapi.chanjet.com
    #畅捷通开放平台appKey
    appKey: ptPrU0YV
    #畅捷通开放平台appSecret
    appSecret: 6C901AFCA78DEC78FCD67D7EA8DC9C0B
    #加解密key
    encryptKey: 9876543210987654
    #长沙银行支付结果推送地址
    backUrl: https://inte-csbank-pay.chanapp.chanjet.com/api/message/test
    #Oauth重定向地址
    redirectUri: https://inte-csbank-pay.chanapp.chanjet.com/api/auth/receiveCode
    #前端url
    frontUrl: http://3810a707ed7f.ngrok.io/api/auth/test
    #撤销订单url
    orderCancelUrl: /directBank/paygate/v0/doOrderCancel.do
    #付款码支付url
    orderPayUrl: /directBank/paygate/v0/orderPay.do
    #查询支付订单url
    queryOrderUrl: /directBank/paygate/v0/orderQueryWithSign.do
    #查询退款订单url
    queryRefundOrderUrl: /directBank/paygate/h5/thirdpartyQueryRefundOrder.do
    #退款url
    requestRefundUrl: /directBank/paygate/h5/thirdpartyRefund.do

